### ISSUE TITLE
不会使用

### ISSUE THREAD

**Issue by JYWXJ327** [17TheWord/nonebot-plugin-group-link-guild#1]
老师你好，这个项目具体操作步骤怎么操作，可以请教一下吗

**Comment by 17TheWord** [comment]
1. 参考 [`NoneBot2 文档`](https://nonebot.dev/docs/quick-start) 搭建简易项目，同时最好实用虚拟环境对依赖分割
2. 在创建好的Bot目录内使用 `nb plugin install nonebot-plugin-group-link-guild` 来安装插件
3. 在 `.env.prod` 或 `.env.dev` 内填写 `Readme` 给出的配置项
    - 依次为：群号、群命令头、频道ID、子频道ID、频道命令头、机器人账号
4. 最后，在机器人目录 `nb run` 启动项目
